version: "3.9"

services:

  golang:
    container_name: my-golang-workspace
    restart: always
    image: golang:1.16.2-alpine3.13
    tty: true # Allocate a pseudo-tty
    shm_size: 1g # shared memory size. Unit is optional and can be b (bytes), k (kilobytes), m (megabytes), or g (gigabytes).
    working_dir: /usr/src/myapp # source code directory
    ports:
      - target: 80      # the port inside the container
        published: 8081 # the publicly exposed port
        protocol: tcp   # the port protocol (tcp or udp)
        mode: host      # 'host' for publishing a host port on each node, or 'ingress' for a swarm mode port to be load balanced.
      - target: 443
        published: 8444
        protocol: tcp
        mode: host
    volumes:
      - ./source:/usr/src/myapp # source code directory volume mapping
